# -*- coding: utf-8 -*-
"""bayesrs.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16uj8LbvbxnSymGCvVz0hu6RzFRoTahxH
"""
import streamlit as st
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

st.title("Posterior al estilo Bayes (1763)")

st.write("""
Esta app calcula la posterior de Bayes usando discretización, como Bayes lo hizo en su ensayo *An Essay towards Solving a Problem in the Doctrine of Chances*.
La fórmula discreta es:

P(x_i | D) = x_i^p * (1-x_i)^q / Σ_j (x_j^p * (1-x_j)^q)
""")

# Entradas de usuario
p = st.number_input("Número de éxitos (p)", min_value=0, value=7, step=1)
q = st.number_input("Número de fracasos (q)", min_value=0, value=3, step=1)
intervalos = st.number_input("Número de intervalos para discretización", min_value=2, value=10, step=1)

# Discretización de x
x_values = np.linspace(0, 1, intervalos + 1)
f_values = x_values**p * (1 - x_values)**q

# Normalización (posterior discreta)
posterior_prob = f_values / np.sum(f_values)

# Crear tabla
tabla = pd.DataFrame({
    "x_i": x_values.round(2),
    "x_i^p*(1-x_i)^q": f_values.round(6),
    "P(x_i | D)": posterior_prob.round(4)
})

st.subheader("Tabla de posterior discreta")
st.dataframe(tabla)

# Gráfica estilo histórico
fig, ax = plt.subplots()
ax.bar(x_values, posterior_prob, width=0.05, color='skyblue', edgecolor='black')
ax.set_xlabel("x_i")
ax.set_ylabel("Probabilidad aproximada")
ax.set_title(f"Posterior de Bayes discreta (p={p}, q={q})")
st.pyplot(fig)

# Probabilidad para un valor específico
x_val = st.slider("Selecciona x para ver P(x_i | D)", 0.0, 1.0, 0.7, 0.01)
idx = (np.abs(x_values - x_val)).argmin()
st.write(f"Probabilidad aproximada para x ≈ {x_values[idx]:.2f}: {posterior_prob[idx]:.4f}")
