# -*- coding: utf-8 -*-
"""bayesrs.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16uj8LbvbxnSymGCvVz0hu6RzFRoTahxH
"""
import streamlit as st

st.title("Posterior de Bayes: estilo histórico vs moderno")

# Versión histórica en LaTeX
st.subheader("Versión histórica (discretizada)")

st.latex(r"""
P(x_i \mid D) = \frac{x_i^p (1-x_i)^q}{\sum_j x_j^p (1-x_j)^q}
""")

# Versión moderna en LaTeX
st.subheader("Versión moderna (continua, Teorema de Bayes)")

st.latex(r"""
P(x \mid D) = \frac{P(D \mid x) P(x)}{\int_0^1 P(D \mid x) P(x) dx}
""")
